version: '3.7'

services:
  yobagpt_bot:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    container_name: yobagpt_bot
    command: python main.py
    environment:
      - LOG_LEVEL=INFO